apiVersion: apps/v1
kind: Deployment
metadata:
  name: labgke
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: redis
        image: redis
        ports:
          - containerPort: 6379
            name: redis
            protocol: TCP
      - name: app
        image: "gcr.io/valheim-306722/myfirstapp:2.0"
        env:
        - name: NAME
          value: "Diego - Desafio feito com Sucesso!"
        - name: "REDIS_HOST"
          value: "localhost"
        ports:
         - containerPort: 80